name: Build/release

on:
  push:
    branches:
      - master
    tags:
        - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
        
      - name: Build app # install yarn deps
        run: yarn install

      - name: Build app # build the app
        run: yarn make:macos

      - name: Publish release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/zip/darwin/x64/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: out/make/zip/darwin/x64/*.zip